### PR TITLE
added line 2 to the readme file to try again at inviting peers

### PR DESCRIPTION
**Pull request by maleficsydney**
added line 2 to my readme for you to review

### CODE REVIEW

**Review by dlwill12 — CHANGES_REQUESTED** [review]
Hello my friends

**Comment by kylekundivich** [comment]
Looks good, no changes needed

**Review by dlwill12 — APPROVED** [review]

**Review by kylekundivich — COMMENTED** [review]
Excellent.

**Review by kylekundivich — COMMENTED** [review]
Ok Computer

**Pull request merged**
